name: build flutter web
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            flutter-version: '3.13.9'
#      - run: echo '${{ secrets.SECRET_KEYS_CONTENTS }}' >> keys.json

        env:
          SECRET_KEYS_CONTENTS: ${{ secrets.SECRET_KEYS_CONTENTS }}
      - run: echo $SECRET_KEYS_CONTENTS >> keys.json
#      - run: cat keys.json
      - run: |
          flutter pub get
          flutter config --enable-web
          flutter analyze
          flutter build web --release --dart-define-from-file=keys.json
#      - run: flutter config --enable-web
#      - run: flutter analyze
#      - run: flutter build web --release --dart-define-from-file=keys.json
#      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
      - name: Display structure of build files
        run: ls -R
        working-directory: ./web
