name: build flutter web
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            flutter-version: '3.13.9'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --release
